name: 🔒 Main branch

on:
  push:
    branches:
      - main

env:
  VERSION: v0.${GITHUB_RUN_NUMBER}

jobs:
  make:
    name: Make and release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --silent
      - name: Make the project
        run: yarn make
      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${VERSION}
          release_name: Release ${VERSION}
          draft: true
          prerelease: false
      - name: Upload Windows installer
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/make/squirrel.windows/x64/Sugoi Chatbot-0.0.0 Setup.exe
          asset_name: sugoi-chatbot-setup.exe
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Upload Windows zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/make/zip/win32/x64/Sugoi Chatbot-win32-x64-1.0.0.zip
          asset_name: sugoi-chatbot-${VERSION}-win32-x64.zip
          asset_content_type: application/vnd.microsoft.portable-executable
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
