name: 🔒 Main branch

on:
  push:
    branches:
      - main

jobs:
  make:
    name: Make
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - run: yarn install --silent
      - name: Make the project
        run: yarn make
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: out/make/squirrel.windows/x64

  